global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'academic-backend'
    static_configs:
      - targets: ['backend:8090']
    metrics_path: '/api/metrics'
